urls.py
from django.conf.urls.defaults import *
from compsoc.feeds import *
from compsoc import settings
from compsoc.cms.views import handle,list,games,attachments
from compsoc.search.views import search
from django.contrib.auth.models import User
from compsoc.rest import *
from functools import partial
import new

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from memberinfo.models import ShellAccount,DatabaseAccount,Quota

# inject extra context into the index method (WHY DOES IT HAVE THIS ARGUMENT IF IT DOESN'T LET YOU USE IT!?)
def create_index(index):
    def index_with_extra_context(*args, **kwargs):
        extra_context = {
            'guest_request_count':User.objects.filter(is_active=False,member__guest=True).count(),
            'shell_request_count':ShellAccount.objects.filter(status='RE').count(),
            'database_request_count':DatabaseAccount.objects.filter(status='RE').count(),
            'quota_request_count':Quota.objects.filter(status='RE').count(),
        }
        kwargs['extra_context'] = extra_context
        return index(*args, **kwargs)

    return index_with_extra_context

admin.site.index = create_index(admin.site.index)

# See feeds.py for details
feeds = {
    'news': LatestNews,
    'news/atom': LatestAtomNews,
    'events': NextEvents,
    'events/atom': NextAtomEvents,
    'signups': LatestSignups,
    'seating': LatestSeatingRevisions,
    'minutes': LatestMinutes,
    'minutes/atom': LatestAtomMinutes,
    'newsletters': LatestNewsletters,
    'newsletters/atom': LatestNewsletters,
    'tickets': LatestTicketChanges,
    'pagerevisions': LatestPageRevisions,
}

urlpatterns = patterns('',
    (r'^', include('compsoc.comms.urls')),
    (r'^elections/', include('elections.urls')),
    (r'^member/', include('compsoc.memberinfo.urls')),
    (r'^events/', include('compsoc.events.urls')),
    (r'^tournaments/', include('compsoc.tournaments.urls')),
    #(r'^irc/', include('compsoc.choob.urls')),
    (r'^tickets/', include('compsoc.tracker.urls')),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    
    (r'^admin/cms/page/(?P<page_id>\d+)/$','compsoc.cms.admin_views.add_edit'),
    (r'^admin/cms/pagerevision/(?P<rev_id>\d+)/$','compsoc.cms.admin_views.revision'),
    (r'^admin/cms/page/add/$','compsoc.cms.admin_views.add_edit'),
    (r'^admin/cms/page/move/(?P<page_id>\d+)/$', 'compsoc.cms.admin_views.move'),
    (r'^admin/memberinfo/guests/$','compsoc.memberinfo.admin_views.guest_list'),
    (r'^admin/memberinfo/accounts/$','compsoc.memberinfo.admin_views.account_list'),
    (r'^admin/memberinfo/acceptguest/(?P<user_id>\d+)/$','compsoc.memberinfo.admin_views.accept_guest'),
    (r'^admin/memberinfo/rejectguest/(?P<user_id>\d+)/$','compsoc.memberinfo.admin_views.reject_guest'),
    (r'^admin/events/email/(?P<event_id>\d+)/$','compsoc.events.admin_views.email_signups'),
    (r'^admin/events/location/unify/(?P<location_id>\d+)/$','compsoc.events.admin_views.unify'),
    (r'^admin/(.*)', admin.site.root),

# django stuff for authentication
    (r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^logout/', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    (r'^password/', 'django.contrib.auth.views.password_change', {'template_name':'password.html','post_change_redirect':'/'}),
# doesn't work for no reason
    (r'^password_reset/$', 'django.contrib.auth.views.password_reset'),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^password_reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^password_reset/complete/$', 'django.contrib.auth.views.password_reset_complete'),

    (r'^info_map/$',list),
    (r'^game_servers/$',games),
    (r'^search/$', search),

    #XML REST API
    url(r'^xml/user/(\d+)/$', xml_user),
    url(r'^xml/game/(.*?)/?$', xml_games),
    (r'^tinymce/', include('tinymce.urls')),
)

# Some legacy link compatibility. I hope this doesn't break anything

if settings.LEGACY_SITE:
    urlpatterns += patterns('',
    	(r'^society/events/', include('compsoc.events.urls')),
    	(r'^society/members/website', include('compsoc.memberinfo.urls')),
    	(r'^auth/logout', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    )
    urlpatterns += patterns('django.views.generic.simple',
        ('^services/codd/tos/?$', 'redirect_to', {'url': '/cms/about/services/codd/tos/'}),
        ('^society/events/rss2.0/$', 'redirect_to', {'url': '/feeds/events/'}),
        ('^society/news/rss2.0/$', 'redirect_to', {'url': '/feeds/news/'}),
        ('^society/minutes/rss2.0/$', 'redirect_to', {'url': '/feeds/minutes/'}),
        ('^society/events/ical/$', 'redirect_to', {'url': '/events/ical/'}),
        ('^society/contact/$', 'redirect_to', {'url': '/cms/contact/'}),
        ('^society/exec/$', 'redirect_to', {'url': '/cms/contact/'}),
        ('^society/newsletters/$', 'redirect_to', {'url': '/newsletters/1/'}),
        ('^society/minutes/$', 'redirect_to', {'url': '/minutes/1/'}),
        ('^society/news/$', 'redirect_to', {'url': '/news/1/'}),
        ('^society/members/$', 'redirect_to', {'url':'/member'}),
        ('^society/members/list/$', 'redirect_to', {'url': '/member/list/'}),
        ('^society/$', 'redirect_to', {'url': '/cms/about/'}),
        ('^gaming/$', 'redirect_to', {'url': '/cms/about/gaming/'}),
        ('^gaming/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/gaming/%(id)s/'}),
        ('^gaming/lans/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/gaming/lans/%(id)s/'}),
        ('^academic/$', 'redirect_to', {'url': '/cms/about/academic/'}),
        ('^academic/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/academic/%(id)s/'}),
        ('^socials/$', 'redirect_to', {'url': '/cms/about/socials/'}),
        ('^socials/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/socials/%(id)s/'}),
        ('^services/$', 'redirect_to', {'url': '/cms/about/services/'}),
        ('^services/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/services/%(id)s/'}),
    )   

# if we are debugging serve the static content locally
# when deployed we use an http server to do this
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT } ),
        (r'^(?P<path>cms/.*/attachment/[^/]+)/$', 'django.views.static.serve', { 'document_root':settings.MEDIA_ROOT } ),
        (r'^ajax/lvsch/$','django.views.generic.simple.redirect_to',{'url':'http://search.warwick.ac.uk/'}),
        (r'^sitebuilder2$','django.views.generic.simple.redirect_to',{'url':'http://www2.warwick.ac.uk/sitebuilder2/'}),
    )

# this goes afterwards to make sure it doesn't catch urls of the form cms/.*/attachment/foo$  this currently has problems with cms/.*/attachment/crap/attachment/foo
urlpatterns += patterns('',
    (r'^cms/(?P<url>.*)/attachment/$', attachments),
    (r'^cms/(?P<url>.*)/$',handle),
)

cms/models.py
from django.db import models
from urllib import urlopen
from compsoc.search import register
from compsoc.settings import GAMING_SERVER, MEDIA_ROOT
from django.db.models.fields.files import FieldFile
from django.db import IntegrityError

import os

# set timeout - note this should be written for python 3k
#import socket
#socket.setdefaulttimeout(0.1)

class PageAlreadyExists(Exception):
    """
    Small class for use in forward checking uniqueness for CMS pages
    """
    # This could be properly nested as a subclass exception, but the
    # code for that is unneccessarily confusing for the gains.
    def __init__(self, value):
        self.value = value
    def __str__(self):
        return repr(self.value)

class Page(models.Model):
    slug = models.CharField(max_length=30, unique=True)
    
    def __unicode__(self):
            return self.slug

    def get_data(self):
        return self.pagerevision_set.latest('date_written')

    def text(self):
        # This is to allow templates dealing with both Communications and
        # Pages to use the same methods.
        return self.get_data().text

    def title(self):
        return self.get_data().title

    def login(self):
        return self.get_data().login

    def get_siblings_and_self(self):
        parent_slug = '/'.join(self.slug.split('/')[:-1])
        peers = []

        child_prefix = parent_slug

        if parent_slug != "":
            child_prefix += '/'

        for p in Page.objects.filter(slug__startswith=child_prefix):
            if p.slug[len(child_prefix):].count('/') == 0:
                peers.append(p)
        return peers

    def get_children(self):
        url = self.slug + '/'
        children = []
        for p in Page.objects.filter(slug__startswith=url):
            if p.slug[len(url):].count('/') == 0:
                children.append(p)
        return sorted(children, key=lambda x: x.title())

    def get_absolute_url(self):
        return "/cms/%s" % self.slug

    def move(self, destination, with_attachments=True, with_children=True):
        """
        Moves a page to a new location. As well as changing the slug, it
        has the ability to move attached items and children also. 
        Will error if the root page cannot be moved, will return a list
        of children Pages that couldn't be moved.
        NOTE: This will always call self.save()
        """
        # we really should just check uniqueness first
        if Page.objects.filter(slug=destination):
            raise PageAlreadyExists('There is already a page at %s' % destination)

        # also make sure we have the children first..
        if with_children: children = self.get_children()
        self.slug = destination
        self.save()

        # now remember to update the attachments
        if with_attachments:
            for a in self.attachment_set.iterator():
                a.move(self, save=True)

        if with_children:
            failed = []
            for child in children:
                suffix = child.slug.rstrip('/').split('/')[-1]
                # disjointed pages can exist, we might end up moving a 
                # child to somewhere that already exists, in this case we note
                # that one for return
                try:
                    child.move("%s/%s" % (destination, suffix))
                except PageAlreadyExists:
                    failed.append(child)
            return failed

register(Page, ['title','text'])

class MovableFieldFile(FieldFile):
    """
    An extension to the standard FieldFile with the added ability to be moved/renamed.
    """
    def move(self, destination, save=False):
        """
        Will move the file on disk and update the model to reflect this.
        """
        self._require_file()

        old_location = self._name
        self._name = self.storage.save(destination, self.file)
        setattr(self.instance, self.field.name, self.name)

        # Update the filesize cache
        self._size = len(self.file)

        self.storage.delete(old_location)
        if save: self.instance.save()

class Attachment(models.Model):
    page = models.ForeignKey(Page)
    title = models.CharField(max_length=50)

    def upload_path(self, filename, *args, **kwargs):
        """
        Decides where to save the file, based on the page it's
        attached to.
        """
        return "cms/%s/attachment/%s" % (self.page.slug, filename)

    file = models.FileField(upload_to=upload_path)
    file.attr_class = MovableFieldFile

    def __unicode__(self):
        return self.file.name

    def get_absolute_url(self):
        return "/%s" % self.file.name

    def move(self, destination_page, save=False):
        """
        Updates the file field and moves physical file to reflect a new page.
        Useful for updating attachments when you move their related page.
        """
        name = self.file.name.rstrip('/').split('/')[-1]
        self.page = destination_page
        self.file.move("cms/%s/attachment/%s" % (destination_page.slug, name), save=save)

class PageRevision(models.Model):
    page = models.ForeignKey(Page)
    title = models.CharField(max_length=30)
    text = models.TextField()
    comment = models.CharField(max_length=30)
    date_written = models.DateTimeField()
    login = models.BooleanField()

    def __unicode__(self):
            return self.title

class Game(models.Model):
    title = models.CharField(max_length=255)
    port = models.IntegerField()

    def __unicode__(self):
        return self.title

    def is_online(self):
        try:
            urlopen("http://%s:%i"%(GAMING_SERVER,self.port)).close()
            return True
        except IOError:
            return False

cms/views.py
from django.shortcuts import render_to_response,get_object_or_404,get_list_or_404
from django.http import HttpResponseRedirect
from compsoc.cms.models import *
from collections import defaultdict
from django.template import RequestContext
from compsoc.shortcuts import *
from compsoc.settings import GAMING_SERVER, MEDIA_ROOT
from django import forms
from django.forms import ModelForm

def cleanse(l):
    return map(lambda p: (p.get_absolute_url(),p.get_data().title),l)

def lookup(l):
    breadcrumbs = [('/','home')]
    for url in l:
        try:
            page = Page.objects.get(slug=url)
            breadcrumbs.append(
                (page.get_absolute_url(),page.get_data().title))
        # There may not be a parent, if so, we want
        except Page.DoesNotExist: pass
    return breadcrumbs

class AttachmentForm(ModelForm):
    class Meta:
        model = Attachment
        exclude = ('page')

def attachments(request, url):
    """
    Lists attachments for a page, and presents an upload form.
    """
    page = get_object_or_404(Page, slug=url)
    attachments = Attachment.objects.filter(page=page)

    if request.method == 'POST':
        attachment = Attachment(page=page)
        form = AttachmentForm(request.POST, request.FILES, instance=attachment)
        if form.is_valid(): form.save()
    else:
        form = AttachmentForm()

    stash = {
        'slug':url,
        'title':url,
        'attachments':attachments,
        'form':form,
    }
    return render_to_response('cms/attachments.html', stash,
            context_instance=RequestContext(request,{},[path_processor]))

def handle(request,url):

    # breadcrumbs
    split = url.split('/')
    breadcrumbs,prefix = [],split[0]
    for item in split[1:]:
        breadcrumbs.append(prefix)
        prefix += '/' + item
    breadcrumbs.append(prefix)

    try:
        page = Page.objects.get(slug=url)
    except Page.DoesNotExist:
        dict = {
            'slug':url,
            'breadcrumbs':lookup(breadcrumbs),
        }
        return render_to_response('cms/does_not_exist.html',dict,
            context_instance=RequestContext(request,{},[path_processor]))

    data = page.get_data()

    if data.login and not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')

    # find the siblings that go before and after
    sibs = sorted(page.get_siblings_and_self(), key=lambda x: x.title())

    dict = {
        'page_id':page.id,
        'title':data.title,
        'text':data.text,
        'siblings':[(p.get_absolute_url(),p.get_data().title,p.slug == prefix) for p in sibs],
        'children':cleanse(page.get_children()),
        'breadcrumbs':lookup(breadcrumbs),
        'slug': url,
    }
    return render_to_response('cms/page.html',dict,
        context_instance=RequestContext(request,{},[path_processor]))

def list(request):
    def rec(page):
        '''
            Recursively generates a list of pages for a site map
        '''
        # If anyone knows a way of using sane tags without shoving this
        # in the view, please rewrite
        val = '<a href="%s">%s</a>' % (page.get_absolute_url(),page.title())
        pages = reduce(lambda x,y: x+y,map(rec,page.get_children()),[])
        return [val,pages] if pages else [val]

    return render_to_response('cms/list.html',{
        'list':rec(get_object_or_404(Page,slug='about')) + rec(get_object_or_404(Page,slug='contact')),
    },context_instance=RequestContext(request,{},[path_processor]))

def games(request):
    return render_to_response('cms/games.html',{
        'games':get_list_or_404(Game),
        'server':GAMING_SERVER,
    },context_instance=RequestContext(request,{},[path_processor]))
    

templates/cms/admin/addedit.html
{% extends "cms/admin/base.html" %}

{% block morehead %}
    <script type="text/javascript">
//<![CDATA[
        $(document).ready(function() {
            $("#id_comment").click(function(event){
                $("#id_comment").attr('value','')
            });
            $('#id_text').keypress(reloadPreviewDiv);
            reloadPreviewDiv();
        });
<!--

/*
 * This is the orginial function from Stuart Langridge at http://www.kryogenix.org/
 */
 
/*
* This is the update function from Jeff Minard - http://www.jrm.cc/
*/
function superTextile(s) {
    var r = s;
    // quick tags first
    qtags = [['\\*', 'strong'],
             ['\\?\\?', 'cite'],
             ['\\+', 'ins'],  //fixed
             ['~', 'sub'],   
             ['\\^', 'sup'], // me
             ['@', 'code']];
    for (var i=0;i<qtags.length;i++) {
        ttag = qtags[i][0]; htag = qtags[i][1];
        re = new RegExp(ttag+'\\b(.+?)\\b'+ttag,'g');
        r = r.replace(re,'<'+htag+'>'+'$1'+'</'+htag+'>');
    }
    // underscores count as part of a word, so do them separately
    re = new RegExp('\\b_(.+?)_\\b','g');
    r = r.replace(re,'<em>$1</em>');
    
    //jeff: so do dashes
    re = new RegExp('[\s\n]-(.+?)-[\s\n]','g');
    r = r.replace(re,'<del>$1</del>');

    // links
    re = new RegExp('"\\b(.+?)\\(\\b(.+?)\\b\\)":([^\\s]+)','g');
    r = r.replace(re,'<a href="$3" title="$2">$1</a>');
    re = new RegExp('"\\b(.+?)\\b":([^\\s]+)','g');
    r = r.replace(re,'<a href="$2">$1</a>');

    // images
    re = new RegExp('!\\b(.+?)\\(\\b(.+?)\\b\\)!','g');
    r = r.replace(re,'<img src="$1" alt="$2">');
    re = new RegExp('!\\b(.+?)\\b!','g');
    r = r.replace(re,'<img src="$1">');
    
    // block level formatting
    
        // Jeff's hack to show single line breaks as they should.
        // insert breaks - but you get some....stupid ones
        re = new RegExp('(.*)\n([^#\*\n].*)','g');
        r = r.replace(re,'$1<br />$2');
        // remove the stupid breaks.
        re = new RegExp('\n<br />','g');
        r = r.replace(re,'\n');
    
    lines = r.split('\n');
    nr = '';
    for (var i=0;i<lines.length;i++) {
        line = lines[i].replace(/\s*$/,'');
        changed = 0;
        if (line.search(/^\s*bq\.\s+/) != -1) { 
            line = line.replace(/^\s*bq\.\s+/,'\t<blockquote>')+'</blockquote>'; 
            changed = 1; 
        }
        
        // jeff adds h#.
        if (line.search(/^\s*h[1|2|3|4|5|6]\.\s+/) != -1) { 
            re = new RegExp('h([1|2|3|4|5|6])\.(.+)','g');
            line = line.replace(re,'<h$1>$2</h$1>');
            changed = 1; 
        }
        
        if (line.search(/^\s*\*\s+/) != -1) { line = line.replace(/^\s*\*\s+/,'\t<liu>') + '</liu>'; changed = 1; } // * for bullet list; make up an liu tag to be fixed later
        if (line.search(/^\s*#\s+/) != -1) { line = line.replace(/^\s*#\s+/,'\t<lio>') + '</lio>'; changed = 1; } // # for numeric list; make up an lio tag to be fixed later
        if (!changed && (line.replace(/\s/g,'').length > 0)) line = '<p>'+line+'</p>';
        lines[i] = line + '\n';
    }
    
    // Second pass to do lists
    inlist = 0; 
    listtype = '';
    for (var i=0;i<lines.length;i++) {
        line = lines[i];
        if (inlist && listtype == 'ul' && !line.match(/^\t<liu/)) { line = '</ul>\n' + line; inlist = 0; }
        if (inlist && listtype == 'ol' && !line.match(/^\t<lio/)) { line = '</ol>\n' + line; inlist = 0; }
        if (!inlist && line.match(/^\t<liu/)) { line = '<ul>' + line; inlist = 1; listtype = 'ul'; }
        if (!inlist && line.match(/^\t<lio/)) { line = '<ol>' + line; inlist = 1; listtype = 'ol'; }
        lines[i] = line;
    }

    r = lines.join('\n');
    // jeff added : will correctly replace <li(o|u)> AND </li(o|u)>
    r = r.replace(/li[o|u]>/g,'li>');

    return r;
}

// Richard Warburton 2009
function reloadPreviewDiv() { 
    $('#previewcomment').html(superTextile($('#id_text').val()));
}

//-->
//]]>
</script>

    </script>
{% endblock %}

{% block sidebar %}
    <ul>
        <li>
            <h2>CMS Admin</h2>
            <ul>
		<li><a href="/cms/{{ slug }}/">View Page</a></li>
		<li><a href="/admin/cms/page/move/{{ id }}/">Move Page</a></li>
                <li><a href="/admin/cms/page/">Page List</a></li>
            </ul>
		</li>
        <li>
            <h2>Revisions</h2>
            <ul>
			    {% for comment,id in comments %}
			        <li><a href="/admin/cms/pagerevision/{{ id }}/">{{ comment }}</a></li>
			    {% endfor %}
            </ul>
		</li>
	</ul>
{% endblock %}

{% block content %}
    {% if form.subject.errors %}
        <ol>
        {% for error in form.message.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
        </ol>
    {% endif %}
	<div class="box">
    {% if id %}
        <form action="/admin/cms/page/{{ id }}/" method="post">
    {% else %}
        <form action="/admin/cms/page/add/" method="post">
    {% endif %}
        <table class="form">
            {{ form.as_table }}
        </table>
        <div class="input">
            <input type="submit" value="submit" />
		</div>
		</form>
        <div class="post">
            <h2 class="title">Preview</h2>
            <p>Note: the following is a subset of textile, and is therefore a 'best effort' preview.</p>
            <div id="previewcomment" class="entry"></div>
        </div>
	</div>
{% endblock %}

templates/cms/admin/base.html
{% extends "base.html" %}

{% block adminu %}class="active"{% endblock %}

templates/cms/admin/move.html
{% extends "cms/admin/base.html" %}

{% block sidebar %}
    <ul>
        <li>
            <h2>CMS Admin</h2>
            <ul>
		<li><a href="/cms/{{ slug }}/">View Page</a></li>
		<li><a href="/admin/cms/page/{{ page_id }}/">Edit Page</a></li>
                <li><a href="/admin/cms/page/">Page List</a></li>
            </ul>
		</li>
	</ul>
{% endblock %}

{% block content %}
	{% if moved_from %}
		{% if success %}
			<h1>Successfully moved "{{ moved_from }}" to "{{ moved_to }}"</h1>
			{% if failed_children %}
				<p>Movement of the following children failed: {{ failed_children|join:", " }}</p>
			{% endif %}
		{% else %}
			<h1>Couldn't move "{{ moved_from }}" to "{{ moved_to }}". There must be a page there already.</h1>
		{% endif %}
	{% endif %}
	<h1>Where would you like to move "{{ slug }}" to?</h1>
	<form action="/admin/cms/page/move/{{ page_id }}/" method="POST">
		{{ form.as_p }}
		<input type="submit" value="move"/>
	</form>
{% endblock %}

templates/cms/admin/view_revision.html
{% extends "cms/admin/base.html" %}

{% load markup %}

{% block sidebar %}
    <ul>
        <li>
            <h2>Revert</h2>
			    <form class="revisions" action="/admin/cms/pagerevision/{{ revision.id }}/" method="post">
			        <input class="comment" type="text" name="comment"/>
			        <input class="submit" type="submit" value="revert to this" />
			    </form>
		</li>
	</ul>
{% endblock %}

{% block content %}
	<div class="post">
		<h2 class="title">{{ revision.title }} @ {{ revision.date_written|date:"D d b, H:i" }}</h2>
		<p class="comment">{{ revision.comment }}</p>
		<div class="entry">
			{{ revision.text|textile }}
		</div>
	</div>
{% endblock%}