events/urls.py
from django.conf.urls.defaults import *
from compsoc.events.models import Location 

urlpatterns = patterns('compsoc.events.views',
    (r'^$','events_list'),
    (r'^calendar/$','calendar_index'),
    (r'^calendar/(?P<delta>-?\d+)/$','calendar'),
    (r'^details/(?P<event_id>\d+)/$','details'),
    (r'^signup/(?P<event_id>\d+)/$','do_signup'),
    (r'^unsignup/(?P<event_id>\d+)/$','do_unsignup'),
    (r'^ical/$','ical_feed'),
    (r'^ical2/$','ical_feed2'),
    (r'^seating/(?P<event_id>\d+)/$', 'seating'),
    (r'^seating/(?P<event_id>\d+)/(?P<revision_no>\d+)/$', 'seating'),
    (r'^location/(?P<object_id>\d+)/$','location'),
    (r'^friends/$','lan_friends'),
    (r'^activity/$','activity'),
)

urls.py
from django.conf.urls.defaults import *
from compsoc.feeds import *
from compsoc import settings
from compsoc.cms.views import handle,list,games,attachments
from compsoc.search.views import search
from django.contrib.auth.models import User
from compsoc.rest import *
from functools import partial
import new

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from memberinfo.models import ShellAccount,DatabaseAccount,Quota

# inject extra context into the index method (WHY DOES IT HAVE THIS ARGUMENT IF IT DOESN'T LET YOU USE IT!?)
def create_index(index):
    def index_with_extra_context(*args, **kwargs):
        extra_context = {
            'guest_request_count':User.objects.filter(is_active=False,member__guest=True).count(),
            'shell_request_count':ShellAccount.objects.filter(status='RE').count(),
            'database_request_count':DatabaseAccount.objects.filter(status='RE').count(),
            'quota_request_count':Quota.objects.filter(status='RE').count(),
        }
        kwargs['extra_context'] = extra_context
        return index(*args, **kwargs)

    return index_with_extra_context

admin.site.index = create_index(admin.site.index)

# See feeds.py for details
feeds = {
    'news': LatestNews,
    'news/atom': LatestAtomNews,
    'events': NextEvents,
    'events/atom': NextAtomEvents,
    'signups': LatestSignups,
    'seating': LatestSeatingRevisions,
    'minutes': LatestMinutes,
    'minutes/atom': LatestAtomMinutes,
    'newsletters': LatestNewsletters,
    'newsletters/atom': LatestNewsletters,
    'tickets': LatestTicketChanges,
    'pagerevisions': LatestPageRevisions,
}

urlpatterns = patterns('',
    (r'^', include('compsoc.comms.urls')),
    (r'^elections/', include('elections.urls')),
    (r'^member/', include('compsoc.memberinfo.urls')),
    (r'^events/', include('compsoc.events.urls')),
    (r'^tournaments/', include('compsoc.tournaments.urls')),
    #(r'^irc/', include('compsoc.choob.urls')),
    (r'^tickets/', include('compsoc.tracker.urls')),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    
    (r'^admin/cms/page/(?P<page_id>\d+)/$','compsoc.cms.admin_views.add_edit'),
    (r'^admin/cms/pagerevision/(?P<rev_id>\d+)/$','compsoc.cms.admin_views.revision'),
    (r'^admin/cms/page/add/$','compsoc.cms.admin_views.add_edit'),
    (r'^admin/cms/page/move/(?P<page_id>\d+)/$', 'compsoc.cms.admin_views.move'),
    (r'^admin/memberinfo/guests/$','compsoc.memberinfo.admin_views.guest_list'),
    (r'^admin/memberinfo/accounts/$','compsoc.memberinfo.admin_views.account_list'),
    (r'^admin/memberinfo/acceptguest/(?P<user_id>\d+)/$','compsoc.memberinfo.admin_views.accept_guest'),
    (r'^admin/memberinfo/rejectguest/(?P<user_id>\d+)/$','compsoc.memberinfo.admin_views.reject_guest'),
    (r'^admin/events/email/(?P<event_id>\d+)/$','compsoc.events.admin_views.email_signups'),
    (r'^admin/events/location/unify/(?P<location_id>\d+)/$','compsoc.events.admin_views.unify'),
    (r'^admin/(.*)', admin.site.root),

# django stuff for authentication
    (r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^logout/', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    (r'^password/', 'django.contrib.auth.views.password_change', {'template_name':'password.html','post_change_redirect':'/'}),
# doesn't work for no reason
    (r'^password_reset/$', 'django.contrib.auth.views.password_reset'),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^password_reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^password_reset/complete/$', 'django.contrib.auth.views.password_reset_complete'),

    (r'^info_map/$',list),
    (r'^game_servers/$',games),
    (r'^search/$', search),

    #XML REST API
    url(r'^xml/user/(\d+)/$', xml_user),
    url(r'^xml/game/(.*?)/?$', xml_games),
    (r'^tinymce/', include('tinymce.urls')),
)

# Some legacy link compatibility. I hope this doesn't break anything

if settings.LEGACY_SITE:
    urlpatterns += patterns('',
    	(r'^society/events/', include('compsoc.events.urls')),
    	(r'^society/members/website', include('compsoc.memberinfo.urls')),
    	(r'^auth/logout', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    )
    urlpatterns += patterns('django.views.generic.simple',
        ('^services/codd/tos/?$', 'redirect_to', {'url': '/cms/about/services/codd/tos/'}),
        ('^society/events/rss2.0/$', 'redirect_to', {'url': '/feeds/events/'}),
        ('^society/news/rss2.0/$', 'redirect_to', {'url': '/feeds/news/'}),
        ('^society/minutes/rss2.0/$', 'redirect_to', {'url': '/feeds/minutes/'}),
        ('^society/events/ical/$', 'redirect_to', {'url': '/events/ical/'}),
        ('^society/contact/$', 'redirect_to', {'url': '/cms/contact/'}),
        ('^society/exec/$', 'redirect_to', {'url': '/cms/contact/'}),
        ('^society/newsletters/$', 'redirect_to', {'url': '/newsletters/1/'}),
        ('^society/minutes/$', 'redirect_to', {'url': '/minutes/1/'}),
        ('^society/news/$', 'redirect_to', {'url': '/news/1/'}),
        ('^society/members/$', 'redirect_to', {'url':'/member'}),
        ('^society/members/list/$', 'redirect_to', {'url': '/member/list/'}),
        ('^society/$', 'redirect_to', {'url': '/cms/about/'}),
        ('^gaming/$', 'redirect_to', {'url': '/cms/about/gaming/'}),
        ('^gaming/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/gaming/%(id)s/'}),
        ('^gaming/lans/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/gaming/lans/%(id)s/'}),
        ('^academic/$', 'redirect_to', {'url': '/cms/about/academic/'}),
        ('^academic/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/academic/%(id)s/'}),
        ('^socials/$', 'redirect_to', {'url': '/cms/about/socials/'}),
        ('^socials/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/socials/%(id)s/'}),
        ('^services/$', 'redirect_to', {'url': '/cms/about/services/'}),
        ('^services/(?P<id>\d+)/$', 'redirect_to', {'url': '/cms/about/services/%(id)s/'}),
    )   

# if we are debugging serve the static content locally
# when deployed we use an http server to do this
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT } ),
        (r'^(?P<path>cms/.*/attachment/[^/]+)/$', 'django.views.static.serve', { 'document_root':settings.MEDIA_ROOT } ),
        (r'^ajax/lvsch/$','django.views.generic.simple.redirect_to',{'url':'http://search.warwick.ac.uk/'}),
        (r'^sitebuilder2$','django.views.generic.simple.redirect_to',{'url':'http://www2.warwick.ac.uk/sitebuilder2/'}),
    )

# this goes afterwards to make sure it doesn't catch urls of the form cms/.*/attachment/foo$  this currently has problems with cms/.*/attachment/crap/attachment/foo
urlpatterns += patterns('',
    (r'^cms/(?P<url>.*)/attachment/$', attachments),
    (r'^cms/(?P<url>.*)/$',handle),
)

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save,post_delete
from django.db.models import Q
from datetime import timedelta,datetime

from compsoc.settings import DATE_FORMAT_STRING,SAME_SECOND_FORMAT
from compsoc.search import register
from compsoc.events import write_file_callback
from compsoc.shortcuts import flatten
from django.contrib.admin.models import LogEntry,ContentType

TARGETS = (
    ('ACA', 'Academic'),
    ('GAM', 'Gaming'),
    ('SCL', 'Social'),
    ('SCT', 'Society'),
)

class EventType(models.Model):
    name = models.CharField(max_length=20)
    info = models.TextField()
    target = models.CharField(max_length=3, choices=TARGETS)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Location(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField()
    image_url = models.CharField(max_length=255, default="/static/img/no_location.png")
    map_loc = models.CharField(max_length=30, blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/events/location/%i/" % self.id

    class Meta:
        ordering = ['name']

class EventManager(models.Manager):
    def in_future(self):
        """
        Get upcoming events which are allowed to be displayed now.
        """
        now = datetime.now()
        return self.filter(finish__gte=now,displayFrom__lte=now).order_by('start')

    def in_future_all(self):
        """
        Get upcoming events, including those that aren't displayed publically yet.
        """
        return self.filter(finish__gte=datetime.now()).order_by('start')

    def for_week(self, date):
        """
        Get events for the whole week containing this date
        """
        # events starting from midnight sunday
        startdate = date - timedelta(days=date.weekday())
        startdate = startdate.replace(hour=0,minute=0,second=0,microsecond=0)
        # ending at midnight sunday
        enddate = startdate + timedelta(days=7)

        return self.filter(finish__gte=startdate, finish__lte=enddate).order_by('start')

class Event(models.Model):
    """
    Represents a single event
    """
    # I'm never using camel case for model fields again :p
    type = models.ForeignKey(EventType)
    location = models.ForeignKey(Location)
    shortDescription = models.CharField(max_length=255, verbose_name="Short Description", help_text="This text is displayed on the events index.")
    longDescription = models.TextField(verbose_name="Long Description", help_text="This text is displayed on the details page for this event.")
    start = models.DateTimeField(default=datetime.now)
    finish = models.DateTimeField(default=lambda:datetime.now() + timedelta(hours=1))
    displayFrom = models.DateTimeField(default=datetime.now, verbose_name="Display From", help_text="This controls when the event will be visible in the index and feeds.")
    cancelled = models.BooleanField()

    objects = EventManager()

    def days(self):
        days = []
        i = self.start.date()
        end = self.finish.date()
        day = timedelta(days=1)
        while i <= end:
            days.append(i)
            i += day
        return days

    def time_string(self):
        s,f = self.start,self.finish
        if s.date() == f.date():
            return s.strftime(DATE_FORMAT_STRING)+" - "+f.strftime(SAME_SECOND_FORMAT)
        else:
            return s.strftime(DATE_FORMAT_STRING)+" - "+f.strftime(DATE_FORMAT_STRING)

    def __unicode__(self):
        return self.type.name + " @ " + self.time_string()

    def is_displayed(self):
        return datetime.now() > self.displayFrom
    
    def is_in_future(self):
        return datetime.now() < self.start

    def is_now_or_later(self):
        return datetime.now() < self.finish

    def is_in_past(self):
        return datetime.now() > self.start

    def is_running(self):
        return self.start < datetime.now() and datetime.now() < self.finish

    def has_signups(self):
        try:
            self.eventsignup
            return True
        except EventSignup.DoesNotExist:
            return False
    
    def signup_total(self):
        try:
            return self.eventsignup.signupsLimit
        except EventSignup.DoesNotExist:
            return 0

    def signup_count(self):
        try:
            return self.signup_set.count()
        except EventSignup.DoesNotExist:
            return 0

    def get_absolute_url(self):
        return "/events/details/%i/" % self.id

    def get_type_name(self):
        return self.type.name

    def last_change_time(self):
        try:
            cct = ContentType.objects.get(name='event')
            return LogEntry.objects.filter(object_id=self.pk,content_type=cct).latest('action_time').action_time.strftime(DATE_FORMAT_STRING)
        except:
            return 0

    def creation_time(self):
        """
        Returns the datetime of the first logentry in the admin history
        """
        ct = ContentType.objects.get(app_label='events', model='event')
        return LogEntry.objects.filter(content_type=ct,object_id=self.id).order_by('action_time')[0].action_time

    def update_count(self):
        """
        Returns the number of modifications in the admin interface to this item
        """
        ct = ContentType.objects.get(app_label='events', model='event')
        return LogEntry.objects.filter(content_type=ct,object_id=self.id).count()

    def is_public_yet(self):
        """
        Returns whether this event should be shown in the public events calendar and feeds yet.
        """
        return self.displayFrom <= datetime.now()

class SteamEvent(Event):
    steam_id = models.CharField(max_length=50)

def future_events(n=5):
    '''
    Generates a list of event types t and events e s.t. e is the
    next event for t.  Restricted to the next n events
    '''
    types = EventType.objects.all()
    future = []
    for type in types:
        try:
            event = type.event_set.filter(finish__gte=datetime.now()).exclude(displayFrom__gte=datetime.now()).order_by('start')[0]
        except IndexError:
            pass
        else:
            future.append((type,event))
    return sorted(future,key=lambda (t,e): e.start)[:n]

register(Event,['shortDescription','longDescription','get_type_name'],order='-start',filter=lambda: Q(displayFrom__lte=datetime.now(), cancelled=False))

post_save.connect(write_file_callback, sender=Event)
post_delete.connect(write_file_callback, sender=Event)
post_save.connect(write_file_callback, sender=SteamEvent)
post_delete.connect(write_file_callback, sender=SteamEvent)

class SeatingRoom(models.Model):
    '''Information a room that people are sat in'''
    room = models.ForeignKey(Location)
    name = models.CharField(max_length=50)
    max_cols = models.IntegerField()
    max_rows = models.IntegerField()

    def __unicode__(self):
        return "%s @ %s" % (self.name,self.room.__unicode__())

# Signup Options seperated from Event to normalise and avoid nullable.
class EventSignup(models.Model):
    """
    This represents the signup options for a particular event,
    e.g Signup limits and time constraints
    This might be renamed to EventSignupOptions
    """
    event = models.OneToOneField(Event)
    signupsLimit = models.IntegerField(verbose_name="Signups Limit", help_text="0 here implies unlimited signups.")
    open = models.DateTimeField()
    close = models.DateTimeField()
    fresher_open = models.DateTimeField(help_text="This allows you to control whether freshers can sign up earlier or later than regular members.")
    guest_open = models.DateTimeField(help_text="This allows you to control whether guests can sign up earlier or later than regular members.")
    # this might be renamed to seating_plan for clarity
    seating = models.ForeignKey(SeatingRoom,blank=True,null=True, verbose_name="Seating Plan", help_text="This determines the number of rows and columns the seating plan will allow for.")

    def has_seating_plan(self):
        try:
            self.seating
            return True
        except SeatingRoom.DoesNotExist:
            return False

    def __unicode__(self):
        return self.event.__unicode__()

# choob will register events if we write them to THE FILE
post_save.connect(write_file_callback, sender=EventSignup)
post_delete.connect(write_file_callback, sender=EventSignup)

class Signup(models.Model):
    event = models.ForeignKey(Event)
    time = models.DateTimeField()
    user = models.ForeignKey(User)
    comment = models.TextField(blank=True)

    class Meta:
        ordering = ["time"]
        unique_together = ("event", "user")

    def __unicode__(self):
        return self.user.username

    def time_form(self):
        return self.time.strftime(DATE_FORMAT_STRING)

post_save.connect(write_file_callback, sender=Signup)
post_delete.connect(write_file_callback, sender=Signup)

class RevisionManager(models.Manager):
    def for_event(self,e):
        return self.filter(event=e).order_by('-number')

class SeatingRevision(models.Model):
    '''Information about a single seating plan revision'''
    event = models.ForeignKey(Event)
    creator = models.ForeignKey(User)
    number = models.IntegerField()
    comment = models.CharField(max_length=30)

    objects = RevisionManager()

    def __unicode__(self):
        return "%i, %s" % (self.number, self.comment)

    def prev(self):
        return SeatingRevision.objects.get(event=self.event,number=self.number-1)

    def users(self):
        return val_users(self.seating_set)

    def added(self):
        '''
        People who were added to the seating plan in the current
        revision.
        Returns an iterable of Seating Objects
        '''
        try:
            return self.seating_set.exclude(user__in=self.prev().users())

templates/events/activity.html
{% extends "events/base.html" %}

{% block ttitle %}Member Activity{% endblock %}

{% block content %}
<h2 class="title">Member Activity</h2>

<p>Number of events attended by members</p>

<table>
    <thead>
    <tr>
        <th>Member</th>
        <th>Events</th>
    </tr>
    </thead>
    <tbody>
    {% for name,count in members %}
        <tr>
            <td>{{ name }}</td>
            <td>{{ count }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/events/alreadysignedup.html
{% extends "events/base.html" %}

{% block content %}
<p class="notification">You are already signed up to {{ event.type.name }}.</p>
{% endblock %}

{% block sidebar %}
    <ul>
        <li>
            <h2>Event</h2>
            <ul>
                <li><a href="/events/details/{{ event.id }}/">Back to event</a></li>
            </ul>
        </li>
	</ul>
{% endblock %}

templates/events/calendar.html
{% extends "events/base.html" %}

{% block ttitle %}Events Calendar{% endblock %}

{% block content %}
<p class="calendar-key">
	<span class="academic">academic</span>
	<span class="social">social</span>
	<span class="gaming">gaming</span>
	<span class="society">society</span>
</p>

<div id="calendar">
	<ul class="calendarnav">
		{% if prev %}
			<li class="prev"><a href="/events/calendar/{{ prev }}">previous week</a></li>
		{% else %}
			<li class="prev"><a href="/events/calendar/-1">previous week</a></li>
		{% endif %}
		{% if next %}
			<li class="next"><a href="/events/calendar/{{ next }}">next week</a></li>
		{% else %}
			<li class="next"><a href="/events/calendar/1">next week</a></li>
		{% endif %}
		<li class="cur"><a href="/events/calendar/">current week</a></li>
	</ul>
	<table>
		<tr>
			<th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th><th>Sun</th>
		</tr>
		{% for week_no,week_contents in events %}
		<tr>
			{% for day,day_contents in week_contents %}
				<td>
					<ul>
						{% if forloop.first %}
							<li class="week">Wk {{ week_no }}</li>
						{% endif %}
						<li class="day">{{ day }}</li>
						{% for event in day_contents %}
							<li class="event {{ event.type.get_target_display|lower }}">
                            {% if event.cancelled %}<del>{% endif %}
                                <a href="/events/details/{{event.id}}" title="{{event.shortDescription}} @ {{ event.time_string }}">{{event.type.name}}</a>
                            {% if event.cancelled %}</del>{% endif %}
                            </li>
						{% endfor %}
					</ul>
				</td>
			{% endfor %}
		</tr>
		{% endfor %}
	</table>
	<ul class="calendarnav">
		{% if prev %}
			<li class="prev"><a href="/events/calendar/{{ prev }}">previous week</a></li>
		{% else %}
			<li class="prev"><a href="/events/calendar/-1">previous week</a></li>
		{% endif %}
		{% if next %}
			<li class="next"><a href="/events/calendar/{{ next }}">next week</a></li>
		{% else %}
			<li class="next"><a href="/events/calendar/1">next week</a></li>
		{% endif %}
		<li class="cur"><a href="/events/calendar/">current week</a></li>
	</ul>
</div>
{% endblock %}

templates/events/cantsignup.html
{% extends "events/base.html" %}

{% block content %}
<p class="notification">You can't yet signup to {{ event.type.name }}.</p>
{% endblock %}

{% block sidebar %}
    <ul>
        <li>
            <h2>Event</h2>
            <ul>
                <li><a href="/events/details/{{ event.id }}/">Back to event</a></li>
            </ul>
        </li>
	</ul>
{% endblock %}

templates/events/comment_fail.html
{% extends "events/base.html" %}

{% block content %}
    <p class="notification">There has been an error in signing up to the {{ event.type }}.</p>
    <div class="entry">
        <ul>
        {{ errors }}
        </ul>
    </div>
{% endblock %}

{% block sidebar %}
    <ul>
        <li>
            <h2>Event</h2>
            <ul>
                <li><a href="/events/details/{{ event.id }}/">Back to event</a></li>
            </ul>
        </li>
	</ul>
{% endblock %}

templates/events/edit_signup.html
{% extends "events/base.html" %}

{% block content %}
	<div class="notification">
	    <form action="/events/signup/{{ event_id }}/" method="post">
	    {{ form.as_p }}
	    <p><input type="submit" value="save" /></p>
	    </form>
	</div>
{% endblock %}

{% block sidebar %}
    <ul>
        <li>
            <h2>Event</h2>
            <ul>
                <li><a href="/events/details/{{ event_id }}/">Back to event</a></li>
            </ul>
        </li>
	</ul>
{% endblock %}

templates/events/future.html
{% if future %}
<li>
    <h2>Upcoming</h2>
    <ul>
        {% for type,event in future %}
            <li><a href="/events/details/{{event.id}}/">{{type.name}}</a></li>
        {% endfor %}
    </ul>
</li>
{% endif %}

templates/events/lan_friends.html
{% extends "events/base.html" %}

{% block ttitle %}LAN Friends{% endblock %}

{% block content %}

<h2 class="title">LAN Friends</h2>

<p>A LAN Friend is someone who you often sit beside at LANs.</p>

<table>
    <thead>
    <tr>
        <th>Member</th>
        <th>LAN Friend</th>
        <th>Score</th>
    </tr>
    </thead>
    <tbody>
    {% for user,friend,score in friends %}
        <tr>
            <td>{{ user.member.name }}</td>
            <td>{{ friend.member.name }}</td>
            <td>{{ score }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/events/list.html
{% extends "events/base.html" %}

{% block ttitle %}Events List{% endblock %}

{% block content %}
<p class="calendar-key">
<b>Key:</b> <span class="eventpast">past event</span>
            <span class="eventrunning">now running</span>
    {% if user.is_staff %} <span class="eventhidden">not yet shown</span>{% endif %}
</p>

<ul id="eventlist">
    {% for week,entries in events %}
    <li><ul class="week">
        <li class="weekno"><span>Week {{ week.week_number }}</span></li>
        <li class="fullweek"><span>{{ week }}</span></li>
        <li class="events"><ul>
            {% for event in entries %}
			<li class="name {% if event.is_running %}eventrunning {% else %}{% if event.is_in_past %}eventpast {% endif %}{% endif %}{% if not event.is_public_yet %}eventhidden{% endif %}"><a href="details/{{ event.id }}">{{ event.type.name }}</a>

            <ul class="{% if not event.is_public_yet %}eventhidden {% endif %}eventdetail">
                <li class="time">{{ event.time_string }}</li>
                <li class="location">Location: {{ event.location }}</li>

                {% if event.has_signups %}
                <li class="signups">Signups: {{ event.signup_count }}/{{ event.signup_total }}</li>
                {% endif %}

                <li class="description">

                {% if event.cancelled %}<del>{% endif %}
                {{ event.shortDescription }}
                {% if event.cancelled %}</del>{% endif %}
                </li>
            </ul></li>
            {% endfor %}
        </ul></li>
    </ul></li>
    {% endfor %}
</ul>
{% endblock %}

templates/events/location_detail.html
{% extends "events/base.html" %}

{% block ttitle %}Location Details for {{ object.name }}{% endblock %}

{% block morehead %}
    {% include "common/maps_head.html" %}
{% endblock %}

{% load markup %}

{% block content %}
	{% if user.is_staff %}<a class="edit" href="/admin/events/location/{{ object.id }}/">Edit</a>{% endif %}
    <h2 class="title">{{ object.name }}</h2>
    <br />
    <img src="{{ object.image_url}}"/>
    <br />
    <hr />
    <br />
<!--
    {# include "common/maps.html" 
    <br />
    <hr />
    <br />#}
-->
    {{ object.description|textile }}

{% endblock %}

templates/events/nonsignup.html
{% extends "events/base.html" %}

{% block content %}
<p class="notification">You aren't signed up up to the {{ event.type.name }}, so you can't unsignup from it!</p>
{% endblock %}

{% block sidebar %}
    <ul>
        <li>
            <h2>Event</h2>
            <ul>
                <li><a href="/events/details/{{ event.id }}/">Back to event</a></li>
            </ul>
        </li>
	</ul>
{% endblock %}

templates/events/seating_size_failure.html
{% extends "events/base.html" %}

{% block content %}
<p class="notification">You have created a seating plan thats too large for {{ event.location }}.
    You are only allowed {{ room.max_rows }} rows and {{ room.max_cols }} columns.
</p>

<p class="notification">Please fix the <a href="/events/seating/{{ event.id }}/">Seating Plan</a>.</p>
{% endblock %}

templates/events/unsignup.html
{% extends "events/base.html" %}

{% block content %}
<p class="notification">Unsignup successful.<br /><a href="/events/details/{{ event_id }}/">Back to event</a></p>
{% endblock %}

{% block sidebar %}
    <ul>
        <li>
            <h2>Event</h2>
            <ul>
                <li><a href="/events/details/{{ event_id }}/">Back to event</a></li>
            </ul>
        </li>
	</ul>
{% endblock %}